CompleteSystemPath: "SIIPExamples.jl/script/4_PowerSimulationsDynamics_examples/Data/omib_sys.json"
FaultsType: ["BranchTrip", "BranchImpedanceChange", "ControlReferenceChange", "GeneratorTrip"]
SimulationParameters:
  TspanStart: 0.0
  TspanEnd: 30.0
  StepSize: 0.001
  AbsTol: 0.000001
  RelTol: 0.001
  TFault: 0.1
  DtMax: 0.02
  Solver: "Rodas4"

all: true

FaultParameters:
    BranchTrip:
      Time: 1.0
      BranchName: "BUS 1-BUS 2-i_1"
    BranchImpedanceChange:
      Time: 7.0
      BranchName: "BUS 1-BUS 2-i_1"
      Multiplier: 2
    ControlReferenceChange:
      Time: 5.0
      Device: "generator-102-1"
      RefValue: 0.5
    GeneratorTrip:
      Time: 3.0
      Device: "generator-102-1"
    LoadChange:
      Time: 1.0
      Device: "load-103-1"
      RefValue: 0.8
    LoadTrip:
      Time: 1.0
      Device: "load-103-1"


OutputParameters:
  OutputFile: "output"
  OutputData: ["generator-102-1"] # buses to export output for
  BusNumber: 102