CompleteSystemPath: "system_data/base_system_3invs.json" 
SimulationParameters:
  TspanStart: 0.0
  TspanEnd: 2.0
  StepSize: 0.001
  AbsTol: 1e-9
  RelTol: 1e-6
  TFault: 0.1
  DtMax: 0.02
  Solver: "Rodas4"  #TODO use this solver, currently hardcoded 
  FaultTime: 1.0 

FaultParameters:
    BranchTrip:
      DeviceName: ["BUS 10-BUS 11-i_15"]
    BranchImpedanceChange:
      DeviceName: ["BUS 7-BUS 8-i_11","BUS 10-BUS 11-i_15"]
      Multiplier: 1.0
    ControlReferenceChange:
      DeviceName:
      RefValue: 0.9
    GeneratorTrip:
      DeviceName: ["generator-18-1"]
    LoadChange:
      DeviceName: ["load101"]
      RefValue: 0.8
    LoadTrip:
      DeviceName: ["load101"]

OutputParameters:
  WriteFile: false  
  OutputFile: "output"
  OutputData: 
    BusNumbers: [1, 1]
    BusData: ["Vm", "Vtheta"]
    DynamicDevices: #["gen2", "gen2"]
    States: #["ir_filter", "ii_filter"]
  